# Generated by Django 4.2.4 on 2023-09-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backgroundImage',
            field=models.ImageField(default='windows-xp-wallpaper-bliss_T5gheWz.jpg', null=True, upload_to=''),
        ),
    ]
