# Generated by Django 4.2.4 on 2023-09-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_users_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='followers',
        ),
    ]
