# Generated by Django 4.2.4 on 2023-09-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.png', null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='backgroundImage',
            field=models.ImageField(default='windows-xp-wallpaper-bliss_T5gheWz.jpg', null=True, upload_to='background'),
        ),
    ]
