# Generated by Django 4.2.4 on 2023-09-24 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='chats',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chats',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
