# Generated by Django 4.2.4 on 2023-09-08 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
