# Generated by Django 4.2.4 on 2023-09-15 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_users_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
