# Generated by Django 4.2.4 on 2023-09-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_likepost_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likepost',
            options={'ordering': ['-created_at']},
        ),
    ]
