# Generated by Django 4.2.4 on 2023-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_likepost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
