# Generated by Django 4.2.4 on 2023-09-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_likepost_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likepost',
            options={},
        ),
    ]
