# Generated by Django 4.2.4 on 2023-10-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_likepost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likepost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
    ]
