# Generated by Django 5.2.3 on 2026-02-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_likepost_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
